### PR TITLE
Concurrency issues raised in PR10

### PR DESCRIPTION
**Pull request by nylar**
This pull request addresses mutex locking issues raised in #10, it also prevents blocking the sender when calling any of the calculation functions.

### CODE REVIEW

**Comment by matzhouse** [comment]
lgtm - but I still think we need to do something about the different ways we're getting metrics and values in to 'c' in the sum and avg code

**Comment by manavo** [comment]
Same as @matzhouse, don't like that in the `avg` case we edit/change `c.metrics` in `send`.

I feel it should all be handled from the processor that's reading from the channel.

**Comment by nylar** [comment]
I'm wondering if the average would even work now. If we get a first average request, stick it in the map and then push it into the channel, and then subsequently get a second request. We only have one map entry (as expected) but now we have two average metrics in the channel.

**Comment by manavo** [comment]
@nylar you're quite possibly right, we could end up with a 2nd avg send call before we have processed the input channel.

**Comment by matzhouse** [comment]
The map entry for the avg is a moving average value - so it can work, we just need to either not put those values onto the channel, or move the calculation into the processor..

unless i'm missing something?

**Comment by nylar** [comment]
Open to changing the name of some of the data structures if there is a more ideal name. :smile:

**Comment by manavo** [comment]
Looks better, good work @nylar! The `input` channel is still unbuffered, but now we have all the `send` calls being goroutines, so we won't block. We just stand to end up with a lot of blocked goroutines while we are processing from the `input` channel.

Goroutines are fairly lightweight, so there's a good chance this isn't an issue. Not sure what your thoughts are @nylar & @matzhouse?

**Comment by matzhouse** [comment]
@manavo yeah my thoughts exactly - re the blocking goroutines, we're looking at sub micro second operations - updating memory and blocks - I would hazard a guess that with out max requests a second (something like 2000) and even at 10 metrics per request, we still end up with 50 uS per metric in the worst case. If this worries anyone then we should benchmark a single metric to make sure that's acceptable.

**Comment by nylar** [comment]
It is a good point to raise and one that Mat and I had discussed. I think we should let it run in a production capacity and see if we need to make it buffered, although because we send so few metrics per request (~5) it might not be a big deal, especially with the mutex locking/unlocking being very quick.

**Comment by manavo** [comment]
Is there any benefit to it being unbuffered?

**Comment by matzhouse** [comment]
@manavo simply, no :) 
it would def add some nice elasticity to it - considering we have minute long spikes, it would help with that. The only thing I can think of that would be a slight disadvantage would be a slight drop in accuracy in the worst case - a full buffer. We would possibly be processing data from the last minute in this minute - but still I think that's a very rare case.

**Comment by manavo** [comment]
That would still happen now thought, right? We still only process 1 thing at a time, so it makes no difference if it is goroutines queued up or values in the channel queued up?

**Comment by matzhouse** [comment]
@manavo yeah good point - goroutines or chan spaces.

Cool - everyone happy? @nylar @manavo

**Comment by nylar** [comment]
Yep :) Happy more when I see it running properly

**Comment by manavo** [comment]
Yep, happy with it!

**Comment by matzhouse** [comment]
Merging.

**Pull request merged**
